spring.application.name=demo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto = update
spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

# JWT Configuration parameters
# ***CHANGE THE VALUES OF THE FOLLOWING PARAMETERS BEFORE DEPLOYING TO PRODUCTION***
jwt.secret.key = superSecretKeySuperSecureThatYouDontKnowWhichIs15061998

jwt.access.token.expiration = 3600000

jwt.refresh.token.expiration = 86400000

jwt.token.registration = false